Gabriel Enzo trabalha na empresa ABC tools. Em um de seus processos, a temperatura y de certo equipamento só está facilmente disponível em condições controladas de operação. Sendo assim, em condições normais, a empresa precisa prever essa temperatura com base em 4 sensores distintos (x1, x2, x3 e x4).

No entanto, suspeita-se que nem todos os sensores contribuem corretamente para a previsão. Assim, Gabriel Enzo é incubido com a tarefa de identificar quais sensores são os mais apropriados para a predição da temperatura.

Ele, então, decide usar um modelo linear com regularização LASSO.

In [11]:
import numpy as np
from sklearn.linear_model import Lasso

np.random.seed(42)
n = 100

# Dados de 100 medições dos sensores
X = np.random.randn(n, 4)

# Verdadeiro modelo: y = 1 + 2*x1 + 3*x3 
theta = np.array([1, 2, 0, 3, 0])  # θ2 = θ4 = 0
y = theta[0] + np.matmul(X, theta[1:]) + np.random.normal(0, 0.3, n) # y medido

print("10 primeiras amostras da Matriz X (medição dos sensores, x1, x2, x3, x4):\n", X[:10])
print("\n10 primeiras amostras do Vetor y (temperatura medida em operação controlada):\n", y[:10])

10 primeiras amostras da Matriz X (medição dos sensores, x1, x2, x3, x4):
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358  0.37569802]
 [-0.60063869 -0.29169375 -0.60170661  1.85227818]
 [-0.01349722 -1.05771093  0.82254491 -1.22084365]
 [ 0.2088636  -1.95967012 -1.32818605  0.19686124]]

10 primeiras amostras do Vetor y (temperatura medida em operação controlada):
 [ 3.45816562  5.08951919 -1.32762874 -3.67673478 -3.88475411  4.32073713
 -3.86203231 -2.04911106  3.47672898 -2.41249931]


In [12]:
# Treina o LASSO
lasso = Lasso(alpha=0.1, fit_intercept=True)
lasso.fit(X, y)

print("Coeficientes verdadeiros:", theta)
print("Coeficientes estimados (LASSO):", np.concatenate(([lasso.intercept_], lasso.coef_)))

Coeficientes verdadeiros: [1 2 0 3 0]
Coeficientes estimados (LASSO): [ 0.98358497  1.88145938  0.          2.93112715 -0.        ]


Dessa forma, dados dos sensores 2 e 4, que não contribuem efetivamente para a predição, são automaticamente filtrados pelo modelo.